services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
      - TZ=America/Sao_Paulo
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/data:/var/opt/mssql
